### ISSUE TITLE
Include a case for `ComplexValue` in the definition of multiplication operator of `Complex` class

### ISSUE THREAD

**Issue by Kapi2910** [yash-srivastava19/Elixir#4]
The ComplexValue class converts any Complex object into ComplexValue when multiplying. But when multiplying ComplexValue with Complex, the following exception is met:
> "Can't do that bro."

The reason for this is that the **Complex class does not allow multiplication with any other class type**. That is, the case of Complex being multiplied with ComplexValue is not handled in the definition of Complex class. Hence, an exception is raised. 
 _compare the multiplication definitions in both classes for reference_

### To recreate the problem, run the code snippet below
```python
z1 = Complex(1, 2)
z2 = ComplexValue(Complex(1, 0))

c = z1 * z2 
print(c)
```

**Comment by yash-srivastava19** [comment]
Sure. I am aware of this. I can create a case for the same, and allow for this to happen. This can be done by changing the multiplication definition, as mentioned in the issue.

**Comment by yash-srivastava19** [comment]
This has been implemented in the latest commit (issue4-patch-1 (SHA: 61bcf1da7f3ad143ffb12bd36a7d89d8fddb9018) ). Thanks for pointing it out
